### ISSUE TITLE
Can't build for kernel 4.9

### ISSUE THREAD

**Issue by clementperon** [lwfinger/rtl8192du#60]
@lwfinger Is there a fix to allow a build on 4.9 ?

The call_read_iter is not defined for kernel 4.9

../rtl8192du-custom/os_dep/osdep_service.c: In function ‘new_sync_read’:
../rtl8192du-custom/os_dep/osdep_service.c:58:15: error: implicit declaration of function ‘call_read_iter’ [-Werror=implicit-function-declaration]
         ret = call_read_iter(filp, &kiocb, &iter);
               ^~~~~~~~~~~~~~

https://github.com/lwfinger/rtl8192du/blob/cad7897fc439eda018e45f9ff6d4e69fe5f1bd61/os_dep/osdep_service.c#L57

**Comment by clementperon** [comment]
why not just call __vfs_read instead of __vfs_read_alt
https://github.com/lwfinger/rtl8192du/blob/cad7897fc439eda018e45f9ff6d4e69fe5f1bd61/os_dep/osdep_service.c#L1089

**Comment by clementperon** [comment]
Pull request opened : https://github.com/lwfinger/rtl8192du/pull/61

**Comment by lwfinger** [comment]
The code in call_read_iter() is

return file->f_op->read_iter(kio, iter);

My preference is to add the code for this routine as found in later kernels conditionally to older kernels. In fact, that change has already been pushed. Let me know if it gives any problems.

**Comment by clementperondevialet** [comment]
Ok I will give it a try
